<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEHRRgdT\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEHRRgdT/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerEHRRgdT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerEHRRgdT\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerEHRRgdT\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'EHRRgdT',
    'container.build_id' => '235a7865',
    'container.build_time' => 1621937263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEHRRgdT');
