<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHd3otmh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHd3otmh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHd3otmh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHd3otmh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHd3otmh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hd3otmh',
    'container.build_id' => 'bad94ff0',
    'container.build_time' => 1635251337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHd3otmh');
