<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJwkH7lv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJwkH7lv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJwkH7lv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJwkH7lv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJwkH7lv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JwkH7lv',
    'container.build_id' => '2bde8022',
    'container.build_time' => 1635326964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJwkH7lv');
