<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Interimaire extends \App\Entity\Interimaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'structure', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'profil', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'blockedUser', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'ncni', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'lieuNaissance', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'sitMat', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'diplome', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'universite', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'salaireBrute', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'agence', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'profession', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'photo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'structure', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'profil', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'blockedUser', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'ncni', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'lieuNaissance', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'sitMat', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'diplome', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'universite', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'salaireBrute', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'agence', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'profession', '' . "\0" . 'App\\Entity\\Interimaire' . "\0" . 'photo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Interimaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule(?string $matricule): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?\App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?\App\Entity\Categorie $categorie): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructure(): ?\App\Entity\Structure
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructure', []);

        return parent::getStructure();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructure(?\App\Entity\Structure $structure): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructure', [$structure]);

        return parent::setStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfil(): ?\App\Entity\Profil
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfil', []);

        return parent::getProfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfil(?\App\Entity\Profil $profil): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfil', [$profil]);

        return parent::setProfil($profil);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockedUser(): ?\App\Entity\BlockedUser
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockedUser', []);

        return parent::getBlockedUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlockedUser(\App\Entity\BlockedUser $blockedUser): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlockedUser', [$blockedUser]);

        return parent::setBlockedUser($blockedUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getNcni(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNcni', []);

        return parent::getNcni();
    }

    /**
     * {@inheritDoc}
     */
    public function setNcni(string $ncni): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNcni', [$ncni]);

        return parent::setNcni($ncni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(\DateTimeInterface $dateNaissance): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuNaissance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuNaissance', []);

        return parent::getLieuNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuNaissance(string $lieuNaissance): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuNaissance', [$lieuNaissance]);

        return parent::setLieuNaissance($lieuNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(string $sexe): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', []);

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession(string $profession): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', [$profession]);

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitMat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitMat', []);

        return parent::getSitMat();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitMat(string $sitMat): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitMat', [$sitMat]);

        return parent::setSitMat($sitMat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiplome(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiplome', []);

        return parent::getDiplome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiplome(string $diplome): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiplome', [$diplome]);

        return parent::setDiplome($diplome);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaireBrute(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaireBrute', []);

        return parent::getSalaireBrute();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalaireBrute(int $salaireBrute): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalaireBrute', [$salaireBrute]);

        return parent::setSalaireBrute($salaireBrute);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(string $photo): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgence(): ?\App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgence', []);

        return parent::getAgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgence(?\App\Entity\Agence $agence): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgence', [$agence]);

        return parent::setAgence($agence);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniversite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniversite', []);

        return parent::getUniversite();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniversite(string $universite): \App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniversite', [$universite]);

        return parent::setUniversite($universite);
    }

}
