<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contrat extends \App\Entity\Contrat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'poste', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateSignature', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'interimaire', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'structure', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'document', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'domaine', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'societe'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'poste', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'dateSignature', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'interimaire', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'structure', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'document', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'domaine', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'societe'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contrat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut(?\DateTimeInterface $dateDebut): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(?\DateTimeInterface $dateFin): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$dateFin]);

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoste(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste', []);

        return parent::getPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoste(?string $poste): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoste', [$poste]);

        return parent::setPoste($poste);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSignature(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSignature', []);

        return parent::getDateSignature();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSignature(?\DateTimeInterface $dateSignature): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSignature', [$dateSignature]);

        return parent::setDateSignature($dateSignature);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterimaire(): ?\App\Entity\Interimaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterimaire', []);

        return parent::getInterimaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterimaire(?\App\Entity\Interimaire $interimaire): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterimaire', [$interimaire]);

        return parent::setInterimaire($interimaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructure(): ?\App\Entity\Structure
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructure', []);

        return parent::getStructure();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructure(?\App\Entity\Structure $structure): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructure', [$structure]);

        return parent::setStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocument(): ?\App\Entity\Document
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocument', []);

        return parent::getDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocument(?\App\Entity\Document $document): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocument', [$document]);

        return parent::setDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?\App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?\App\Entity\Categorie $categorie): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaine(): ?\App\Entity\Domaine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaine', []);

        return parent::getDomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaine(?\App\Entity\Domaine $domaine): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaine', [$domaine]);

        return parent::setDomaine($domaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getSociete(): ?\App\Entity\Societe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSociete', []);

        return parent::getSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setSociete(?\App\Entity\Societe $societe): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSociete', [$societe]);

        return parent::setSociete($societe);
    }

}
