<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agence extends \App\Entity\Agence implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'fixe', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'mobile', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'siteweb', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'nomDG', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'numeroDG', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'isDeleted'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'fixe', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'mobile', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'siteweb', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'nomDG', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'numeroDG', '' . "\0" . 'App\\Entity\\Agence' . "\0" . 'isDeleted'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agence $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getFixe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFixe', []);

        return parent::getFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFixe(string $fixe): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixe', [$fixe]);

        return parent::setFixe($fixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', []);

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile(?string $mobile): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', [$mobile]);

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteweb(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteweb', []);

        return parent::getSiteweb();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteweb(?string $siteweb): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteweb', [$siteweb]);

        return parent::setSiteweb($siteweb);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo(?string $logo): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDG(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDG', []);

        return parent::getNomDG();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDG(string $nomDG): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDG', [$nomDG]);

        return parent::setNomDG($nomDG);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDG(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDG', []);

        return parent::getNumeroDG();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDG(string $numeroDG): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDG', [$numeroDG]);

        return parent::setNumeroDG($numeroDG);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted(bool $isDeleted): \App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$isDeleted]);

        return parent::setIsDeleted($isDeleted);
    }

}
